### ISSUE TITLE
Re-write how the player list/Queue works

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#138]
Right now the player needs the DOM to keep track of songs being played and next/prev track.
But the problem is when the view is changed we lost the DOM state and the Player state is updated with the new view.

My point here is:
Let's say we are in Streams view, here a song is playing and there is a DOM state (.currentSong) where prev/next uses it.

My idea is to use some Data Structure (e.g Lists) where the state and tracks are all in memory/virtual.

**Comment by weblancaster** [comment]
Use http://tidal.com/ queue list as example.

**Comment by Chriz007** [comment]
Can you post a picture of the Queue list? I don't want to register for Tidal to see it.

**Comment by Chriz007** [comment]
Do you mean this?

<img width="401" alt="screen shot 2015-07-09 at 5 31 04 pm" src="https://cloud.githubusercontent.com/assets/12990919/8609914/575844f8-2660-11e5-913f-3ada8bb88529.png">

**Comment by jakejarrett** [comment]
There is a queue button on the bottom left on desktop, Which brings out this sidebar. I believe this is what @weblancaster is referring to
![screenshot from 2015-07-10 10-36-47](https://cloud.githubusercontent.com/assets/5661105/8609982/98249b64-26ef-11e5-8b34-b1bf4ddf89fc.png)

**Comment by Chriz007** [comment]
Oh I see

**Comment by weblancaster** [comment]
Both are right @Chriz007 and @jakejarrett that's exactly what I want/plan to do.

I also want to change the change the track timeline/progress to be how Tidal have theirs.. looks pretty good and is left a bunch of space for the buttons play/pause, previous, next, repeat, shuffle.

**Comment by Chriz007** [comment]
hmm. I'm quite fond of the current layout to be honest. But, if you think thats the best plan, then go ahead. But can you keep the current look of the controls? I like it better than tidals. Also, as I'm playing around with tidal's control bar, I notice some problems. When I want to scrub through the track or click anywhere on the track, I have to make sure I do it correctly, otherwise I end up clicking another track. Another problem you could fix if you *do* implement this is making the queue bar that comes out from the right side, slide out faster. Otherwise, the bar is kind of neat. Those are just my two cents.

**Comment by weblancaster** [comment]
@Chriz007 good points.. let's keep the track progress/bar the way it is.

thanks

**Comment by Chriz007** [comment]
If you *really* want to change it though, just use spotify's layout. This also solves issue #273, #260, and #226. Although for issue #260, I think you should use tidal's queue.
<img width="1263" alt="screen shot 2015-07-10 at 2 40 40 pm" src="https://cloud.githubusercontent.com/assets/12990919/8629645/d859f360-2711-11e5-9ae0-3f3023775cf2.png">

**Comment by Pitros** [comment]
@Chriz007 current player layout is a combination of Spotify and SoundCloud (web) player.

Anyway that tidal's progress bar looks really nice, and my first thought was to bring it to Soundnode. As @Chriz007 said it's sometimes hard to click on it, but YouTube uses familiar solution and that problem doesn't exist there, because area where you click is bigger. 

So it should be easy to implement tidial's player with fix (bigger area for hover and click event).

I might get it working soon.

**Comment by Chriz007** [comment]
Okay, I trust you guys. You guys worked together to make an already amazing app, so I'm confident that you will do your best to make it look good and functional.

**Comment by Pitros** [comment]
Got it working for preview, already looks nice for me, but usability is more important. As well added time elapsed - #273. If someone want to try: [source files](https://github.com/Pitros/soundnode-app/tree/progressbar).

With hover:
![image](https://cloud.githubusercontent.com/assets/6910670/8630749/03b8e068-276a-11e5-9194-5b680939c5f9.png)

Without:
![image](https://cloud.githubusercontent.com/assets/6910670/8630753/0bf9b59a-276a-11e5-98dc-c3c2abda2fb9.png)

**Comment by Chriz007** [comment]
Very cool. But whats the time next to the 1:03/3:27?

**Comment by Chriz007** [comment]
Very cool! I like it.

**Comment by weblancaster** [comment]
That's great @Pitros I really liked.. thanks for working on that so fast.

I just don't know about the decreasing time.. I think you can remove that. Just open a PR so we can checkout locally and test.

**Comment by weblancaster** [comment]
@Chriz007 Those issues you pointed out here https://github.com/Soundnode/soundnode-app/issues/138#issuecomment-120536684

Will actually be resolver when I start/finish how the new Queue will work.. I'm going to use some real data structures to help the future development of new features. e.g shuffle, repeat, etc
