### ISSUE TITLE
[BUG] Stream Only Loads 2 Tracks

### ISSUE THREAD

**Issue by runofthemill** [Soundnode/soundnode-app#214]
After authorizing via Facebook, Soundnode successfully logs me in. Following, Likes, and Playlists tabs pull in correct information, but the stream only pulls in 2 tracks.

OSX 10.10.2
Beta 0.5.1

Uninstalling the app, redownloading, reinstalling, then reauthorizing leads to the same result.

**Comment by jakehh** [comment]
I am unable to listen to any tracks at all (I was able to when the update was released)

If i try to skip forward into the song it will just say "Failed to set 'currentTime'" as the players readyState is HAVE_NOTHING

In the console, it says "Not allowed to load local resource" & uses a file:// url which could be causing the error.

**Comment by jakehh** [comment]
Is there any console logs? (Help -> DevTools in the Application Menu)

**Comment by weblancaster** [comment]
Hey @runofthemill this could be related to your Soundcloud account because it's Soundcloud sending all the tracks you should be receiving but for that you need to be following people that actually post tracks to Soundcloud.

This is not a bug because other parts would break since they share the same method to pull the songs.

try follow more people or access Soundnode with another Soundcloud account if this still happen please let me know.
