### ISSUE TITLE
[FEATURE SUGGESTION] Alternative to infinite scroll

### ISSUE THREAD

**Issue by dntrkv** [Soundnode/soundnode-app#248]
First I wanted to say thanks for starting this project, I've been considering building something like this for a while now but was worried Soundcloud would shut it down like they did with Soundflake (https://medium.com/@padschneider/r-i-p-soundflake-79f7cf5f9d61) but that was an iPhone app so this may slide.

Now for my actual feature request, one thing that really annoys me about Soundcloud is the infinite scroll. I understand the need for it, so a multipage playlist can continuously play without the need to switch pages, I get that. But I have 1000+ likes in my Soundcloud profile and the only way to access my earliest likes is to scroll through 50+ pages which is not only super annoying, but slows down the browser since there are so many elements on the page at once.

So my suggestions are:

a. Classic pagination, like they had on Soundcloud Classic
b. Condensed infinite scroll view with, at the very least, 50 tracks on a page with just artist name and track title. No need for album cover or any unnecessary elements that will slow down the loading times. Clicking on the track will play it and show the album art on the sidebar like on Spotify.

I don't have much Angular experience, but I can give it a shot myself and try implementing this if you guys are interested.

Thoughts?

**Comment by weblancaster** [comment]
Hey @dntrkv thanks for your feedback.. there's some good points on it.

I haven't considered this approach before..Change from infinite scroll to pagination can introduce some complexity (AKA problems) because of the way the playlist works right now.

Although, I started to work on a new way the playlist works to make this sort of change easier to happen..for now I will work on reduce the thumbnails size and info.

thanks again.

**Comment by weblancaster** [comment]
This was done in #251
