### ISSUE TITLE
[Bug] Liked Playlists listing

### ISSUE THREAD

**Issue by DamageESP** [Soundnode/soundnode-app#305]
You can't see your liked playlists in the Playlists tab.

**Comment by Chriz007** [comment]
You should write [BUG] in the front of the title so people know

**Comment by mradionov** [comment]
Playlists tab shows playlists you've created as a SoundCloud user. 

On SoundCloud website there is a separate section with liked tracks, playlists and artists

![selection_021](https://cloud.githubusercontent.com/assets/2007370/10710086/28904fe6-7a50-11e5-9556-eac077ca7fff.jpg)

I think it is a good idea to re-create "Collection". In order to do that it will make sense to separate "your" stuff with general stuff in sidebar:

![selection_022](https://cloud.githubusercontent.com/assets/2007370/10710096/fc693cce-7a50-11e5-9247-ad723e48bda6.jpg)

Now, when collection has it's own menu item, it would be possible to re-create actual collection. We could make use of tabs, like SoundCloud website does it:

![selection_023](https://cloud.githubusercontent.com/assets/2007370/10710099/2f0fd7b4-7a51-11e5-96db-cedb33d690d9.jpg)

What do you think about it?

**Comment by weblancaster** [comment]
@mradionov I liked the idea.. can you move this to a new "issue" as improvement please. thanks.

**Comment by weblancaster** [comment]
@DamageESP yes this is a bug..We will work on it to fix for the next release.

Thank for reporting

**Comment by mradionov** [comment]
@weblancaster , I've created a new issue here https://github.com/Soundnode/soundnode-app/issues/423

In order to fix current issue I think it would be nice to provide descriptive error messages, when there is nothing one the page. For this case it could be: "You have not created any playlists yet"
