### ISSUE TITLE
[Bug] Search not always returning the correct artists

### ISSUE THREAD

**Issue by jakejarrett** [Soundnode/soundnode-app#329]
I believe this bug is introduced by searching users via the tracks api.

The change occured in commit 4495f6280563060bd20e0caf41bf566af6841f6c

How to reproduce-

Search for skrillex, Click any of the returned results, none of them are the artist i was searching for.

![screenshot from 2015-08-25 16-05-59](https://cloud.githubusercontent.com/assets/5661105/9459828/3286aa22-4b43-11e5-87a3-0fe1a6d50f66.png)
![screenshot from 2015-08-25 16-06-02](https://cloud.githubusercontent.com/assets/5661105/9459829/32b3b300-4b43-11e5-8272-eef24caffdc1.png)

**Comment by Chriz007** [comment]
Yeah thats kind of what I was referring to in issue #327 because they would only show random users, so putting a verified mark would help identify the right artist

**Comment by weblancaster** [comment]
I agree with @Chriz007 let's add that to the improvements.

**Comment by Pitros** [comment]
Every of those skrillex would point to official skrillex account, but this line is messed up:
https://github.com/Soundnode/soundnode-app/blob/master/app/public/js/search/searchInputCtrl.js#L39
Should be:
`$state.go('profile', {id: this.user.id});`

@weblancaster @Chriz007 soundcloud does not have verified profiles at all, all we can do is to prioritize profiles with higher subscription plan. 
As well we should revert some of #323 changes, because those returned better seach data (not duplicated like right now).

BTW: Best option would be using API v2, and `/autocomplete` - gives best results. So I wrote to Soundcloud devs, about API and I'm waiting for reply on couple questions as well one about using v2 api.

**Comment by jakejarrett** [comment]
I can write a fix tonight, the error is that were using song ID as the artist ID

**Comment by Chriz007** [comment]
@jakejarrett hey, I just have a quick question. For the info bar for the songs, does it refresh once you've clicked the play button for that track?

**Comment by jakejarrett** [comment]
@Chriz007 i'm not 100% sure, it looks like it pulls the data once you play the song.

**Comment by Chriz007** [comment]
I'm asking this because when I went to check back on my track I posted, It hadn't updated to show more stats
