### ISSUE TITLE
Move stream view down when next song plays

### ISSUE THREAD

**Issue by Chriz007** [Soundnode/soundnode-app#344]
Sometimes I like to keep the songs on continuous play, but when I come back to the app to check the song, I have trouble finding where the song is located. 

![screen shot 2015-09-02 at 6 37 34 pm](https://cloud.githubusercontent.com/assets/12990919/9648941/d2a5593a-51a2-11e5-8416-c6181e6adbf1.png)

**Comment by RampageJack21** [comment]
Not sure if this is related or just me being forgetful but often i just hit play when i launch the app.  It will play songs from artists i follow and allows me to discover music.
After some time, I cannot tell where the current track is being played.  I had scrolled 10 pages and couldn't find the album (only 2 hours had gone by so its not like hundreds of songs have played)

I was  going to suggest an button that would reside in the small album cover art (thumbnail?) (in the above screen shot, its headhunterz album cover).  Hovering over the currently playing album cover would show a semi transparent button which when pressed would quickly bring you to the track so you can "like it" and save it.

**Comment by weblancaster** [comment]
@RampageJack21 I introduced Queue list in the new version.. you will never get lost again.

Although, it's a good point.

**Comment by Chriz007** [comment]
@weblancaster Good implementation of the Queue feature. Although.. How about improving it a little better? Some suggestions:
• Moving the stream view to show the song being played, when it is not in view 
• Not resetting the song when it is already playing, when moving stream view to show the song when clicked from the queue.

But overall, I'd still like this feature to be implemented. Its true I won't be as lost, because I'll have information from the Queue to show me what track I'm playing. However, I would still get lost in the stream, because I would have to scroll to find the song playing.

**Comment by RampageJack21** [comment]
the queue is 20 songs deep,  but in stream mode, i might be scrolling down more than 20 songs, and while the current song finishes, since the next one is out of view, it would make me loose my place when it snaps the view to the next song.  

example scenario:  
I really like the current song that is playing and I can see in the queue that the next one is awful. 
I want to wait until the track i like is finished and then find another track further down in time.  In the situations where you are just a few seconds too late, and the scroll gets reset to the top you'll have to spend that time scrolling to the song that is more than 20 tracks away (thus not shown in the queue) all the while listening to the beginning of the awful track.    

once #259 is implemented and hopefully #356, one would be able to 'like' or 'banish' any track from the navigation player bar.  i wont really need to snap to it for any other reason and the queue got me covered for the next 20 tracks continuously.  

below screen shot with some thoughts
![soundnodescroll](https://cloud.githubusercontent.com/assets/9271427/9811345/718793cc-582b-11e5-939b-cf0bce9be341.PNG)

I think something like the below would be needlessly complicated.  if we implement automatic move of the stream which @Chriz007 is asking for, can we add a drop down box from the settings gear in the top right corner to disable this on an individual level?  I can see situations where I would like auto scroll to be enabled (like when im way to busy to be browsing) and times when i dont.  

if (user has not scrolled since launching the app && next track is out of view)
___scroll to next track out of view
else if (has scrolled in x minutes &&  current track out of view && next track out of view) 
##user might be browsing or has found next track and waiting for current song to end
___dont scroll
else if ( has scrolled in x minutes && current track visible && next track out of view)
##user possibly scrolled back to the top
___scroll to next track out of view

**Comment by jakejarrett** [comment]
Forcing something to scroll doesn't seem ideal (Personally, i wouldn't like it if i was looking for another song in the stream view and it just scrolled back up / down), Maybe if you clicked the album art in the bottom view it could scroll down to the current playing?

**Comment by weblancaster** [comment]
Thanks all for the suggestions..

I like the idea of clicking the the player bar icon/logo and scroll to the current song playing
I agree with @jakejarrett to not have a "always" scroll to song when not in view.

There's also something I'm starting to work on which is options on each track in the Queue, here's the issue number for discussion #342

**Comment by weblancaster** [comment]
Closing this issue since the feature `go to track` was implemented.
