### ISSUE TITLE
[Feature suggestion] Move song times to the right

### ISSUE THREAD

**Issue by Mecharon1** [Soundnode/soundnode-app#358]
Like so: 

![soundnode](https://cloud.githubusercontent.com/assets/14226721/9804362/87b609b4-57f2-11e5-8a7a-5d1dd5b9c32c.png)

This would allow more space for long song titles.

**Comment by Chriz007** [comment]
Hmmm. I'm not sure it looks good moved to the right.. I may be wrong, but I don't know if I want to read the *whole* song's title because of over-excessive words. (I'm going to use the example above):
 
Nutronic - Steps Descend (MDK Remix) (Original mix) *FREE DOWNLOAD* = Click Buy

Plus you can always just hover over the title name if you really want to know what it is. But you may need more opinions on this.

**Comment by Mecharon1** [comment]
Sometimes the actual song's title is really long. For example, Excision & Pegboard Nerds - Bring The Madness (Noisestorm Remix) is the whole name of the song, and it gets cut off. On the flip side, when you have a song with a really short name, it looks weird with the times out in the middle of nowhere. Also, what about Twitch streams that overlay the currently playing song? If someone watching liked the song, they might not be able to Google all of it if it was cut off.

**Comment by Chriz007** [comment]
Did you photoshop the time to right or did you modify the code? If so, can you post another picture onto here to see an example of a song with a long title?

**Comment by Mecharon1** [comment]
I photoshopped it. I can't imagine moving it would be hard to code though.

**Comment by RampageJack21** [comment]
seeing as the title of the song is what gets cut off and not the artist line,  would moving it down a bit make enough clearance for the long titles in larger font?  It seems to me that the 'song time' font is the same size/height as the artist string.  An alternate to moving it to the right would be aligning it with the artist line.  Just a thought, i don't know what i would like better.

**Comment by Pitros** [comment]
I've been trying couple layouts yesterday but I didn't get anything that satisffied me. Here are all your ideas how it might look in app (screenshots from app not photoshop).

Here's preview with really long title and time moved to right
![image](https://cloud.githubusercontent.com/assets/6910670/9812924/5981253a-5881-11e5-9bc8-311e7304a1a7.png)

Time moved to right, but there's min. ~100px margin from title.
![image](https://cloud.githubusercontent.com/assets/6910670/9812951/a3b738e2-5881-11e5-8713-4f45092647cb.png)

And here's the one i like most (with small sneak peak @Chriz007)
![image](https://cloud.githubusercontent.com/assets/6910670/9813022/3909d88c-5882-11e5-8b2d-3643740893fd.png)

Remember that if you maximize window, track title probably wont be cut anymore because there will be plenty of space (at least for 1080p+ screens)

**Comment by Chriz007** [comment]
Now that I have more visual options, I think I like the last one the best @Pitros. Although.. what about one where the time is directly in the middle?

**Comment by Pitros** [comment]
Like that? 

![image](https://cloud.githubusercontent.com/assets/6910670/9816836/ab9835b6-589f-11e5-89f3-3e1888ea207c.png)

![image](https://cloud.githubusercontent.com/assets/6910670/9816849/bef4a6da-589f-11e5-9a56-b67650e4dc50.png)

**Comment by weblancaster** [comment]
yeah I haven't being happy with the "song time" at the middle too, but we had more important features to release so was fine..

Now.. I really liked the third suggestion on by @Pitros https://github.com/Soundnode/soundnode-app/issues/358#issuecomment-139513730

**Comment by weblancaster** [comment]
I don't want to much overload in the right side.. that would draw a lot of attention.

**Comment by Chriz007** [comment]
Oh ok so I think I may have an idea. So lets say that we go with the very last picture that @Pitros shared with us. If we decide to see the song title, we can have the cursor hover over the title, so the title can have a 'marquee' effect and scroll through revealing the rest of the words. Then once you've finished, you take your cursor off the title, and the title resumes its static position.

**Comment by Pitros** [comment]
Already when you hover you get an tooltip, marquee is a bad idea - you waste time to wait till it finally reach desired point. It might just revall all the title in one or two lines on hover and hide anything beneath it.

**Comment by weblancaster** [comment]
No need to show the entire title, the user can just hover the title to have the entire name or go to the song view.
