### ISSUE TITLE
Please add clickable links

### ISSUE THREAD

**Issue by Scarwolf** [Soundnode/soundnode-app#409]
A few months ago I added clickable links, but it hasn't been merged since the links opened in soundnode itself. Could someone please add this feature?

With clickable means I mean clickable for both, the about section and profile descriptions.

**Comment by weblancaster** [comment]
I remember that.. but that solution was too hacky @Scarwolf and would impact in rendering performance.

**Comment by Scarwolf** [comment]
Is there any other good solution you could think of? I'am to unexperienced with node, to come up with something by myself.

**Comment by weblancaster** [comment]
Let me think about it. @jakejarrett and @Pitros

**Comment by mradionov** [comment]
Here is an issue for nw.js https://github.com/nwjs/nw.js/issues/1162, where it is suggested to use [node-open](https://github.com/pwnall/node-open).
It can be used in conjunction with AngularJS built-in filter [linky](https://code.angularjs.org/1.2.14/docs/api/ngSanitize/filter/linky), which extracts most commonly used types of the links from the text and wraps them in `<a>` tag.

Quick example:

```
var open = require('open');

$(document).on('click', 'a[href^="http"]', function (event) {
    open(event.target.href);
    return false;
});
```

There are some issues with *linky* in how it renders HTML content, but I'm sure it is possible to fix. Otherwise, it won't be so difficult to add custom filter to parse links.

**Comment by jakejarrett** [comment]
I don't think linky would be necessary, as this issue relates to links that exist but open inside of soundnode instead of chrome/Firefox etc.

**Comment by mradionov** [comment]
I thought that @Scarwolf was talking about "in text" links like here, which now are rendered as text:

![image](https://cloud.githubusercontent.com/assets/2007370/11854754/12484b5e-a457-11e5-81ae-eee78893c5b4.png)

@jakejarrett , could you please tell me what links are addressed in the issue then?

**Comment by weblancaster** [comment]
@Scarwolf is talking about the links in description for example.

**Comment by Pitros** [comment]
As far as I remember that was the case @mradionov.

**Comment by Scarwolf** [comment]
In fact I was talking about every link you can find (Profile Description of Artists, Song-descriptions,...)
