### ISSUE TITLE
Migrate from NW.js to Electron.js

### ISSUE THREAD

**Issue by weblancaster** [Soundnode/soundnode-app#462]
Electron doesn't need audio codec/lib (this is HUGE!) that way we won't depend on matching the codec version with nw.js version like at the moment, will be easier to update.

Seems like has some pretty good support.

@jakejarrett @Pitros what you guys think?

**Comment by Pitros** [comment]
I've played with electron for a while already, but just a little.

Electron provides precompiled version even for ARM (that means eg. Raspberry Pi), some kind of updater (dunno how it works), better MS Windows integration, as well it's constantly updated - every few days there's a new version (because GitHub owns it) - so in next month's it might be much better than nw.js.

But it will might take some time to migrate (if we do that i would suggest to do the user authentication using node.js, not the app on heroku - that will not require playing with hidden windows etc.).

But from the other side there seems to be some kind of progress on NW.js 13 - now there's alpha 6 available, so imho that's tough decision.

**Comment by weblancaster** [comment]
My only problem with nw.js is the having to include the audio codecs/libs in the build, also the built file for windows and linux are ungly with a bunch of files.. everything compiled in one single exe is the ideal.

**Comment by jakejarrett** [comment]
I'm pretty sure electron is a smaller file size too

It'd be worth trying a build with it to see how they perform in comparison to each other

**Comment by toocool** [comment]
Good idea

**Comment by weblancaster** [comment]
This will happen! I need to clear some time on my agenda to migrate a test case..

**Comment by user741981** [comment]
I came here to suggest that too and fortunately found this post so I'm not the only one thinking that way...

The main reason IMHO is that electron is already very mature and will only get better since there's a lot of buzz around it right now.

Maybe a good start for the migration agenda could be a lookup for all node.js dependencies in the project?!

**Comment by bardiharborow** [comment]
@weblancaster why was this closed? I'd be highly in favour of a Electron.js implementation, as this will clean up a lot of issues, e.g. not being able to fullscreen correctly on Mac. I'm happy to put in most of the work for this if you'd be interested.

**Comment by weblancaster** [comment]
@bardiharborow if you want you can start the work on a new branch https://github.com/Soundnode/soundnode-app/tree/electron-migration and we can go from there.

The bigger reason this did not happen was time and priorities.

**Comment by weblancaster** [comment]
@bardiharborow I'm starting to migrate to Electron and will keep updating here #892

**Comment by weblancaster** [comment]
follow PR #894
