### ISSUE TITLE
Can we pay for this?

### ISSUE THREAD

**Issue by alexbw** [Soundnode/soundnode-app#718]
Seems like a lot of work. How can I pay for a copy or donate in some way?

**Comment by weblancaster** [comment]
It is although contributors have been helping greatly.

also, although I'm glad you see such value in it @alexbw when I chose to build Soundnode was mainly to have fun while solving one of my own problems (not having Soundcloud for desktop) but turned out to be a lot of people problems which I'm happily to continue work on it without requiring any type of payment.

Anyway, Thanks for considering it though :)

**Comment by Ajeey** [comment]
Haha @alexbw, thank you for the thought. But this is an open source software and it is free. You can promote this app though so that the contributors are motivated (as more people would use it) and contribute more.
