### ISSUE TITLE
Bug: Certain Artist Pages don't load Tracks

### ISSUE THREAD

**Issue by dgattey** [Soundnode/soundnode-app#737]
Specifically, Calvin Harris's page gives a `401: Unauthorized` error, making loading his tracks or description impossible. Can't figure out why it's happening either.

**Comment by Pitros** [comment]
Okay, so that's SoundCloud issue. Many api calls returns nothing or empty arrays etc. I don't know if they   did that on purpose or it's just a bug because both api-v2 and offical api doesn't work as it should. 

As well if your would try to run some API calls that previously worked, now those won't work because those are not calld by SC website scripts. So API-V2 works partialy for us.

I asked SC devs trough twitter about that, but probably they won't answer.

**Comment by dgattey** [comment]
Hmm, interesting. Seems weird that their API would just fail for certain profiles, but makes sense.
