### ISSUE TITLE
Too many redirects or file not found

### ISSUE THREAD

**Issue by ignusvermaak** [Soundnode/soundnode-app#858]
Hi

Soundnode is not playing this morning, pasted the error logs from the dev tool.

`User is saved
bundle.js:16 Download the React DevTools for a better development experience: https://fb.me/react-devtools
https://i1.sndcdn.com/artworks-000179163540-e7hjt2-t300x300.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
https://api.soundcloud.com/tracks/269032795/stream?client_id=342b8a7af638944906dcdb46f9d56d98 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
file:///var/folders/sk/snm6bq6s697dwtlp3wsg0_ww0000gn/T/.org.chromium.Chromium.5gMscg/public/js/vendor/jquery.min.map Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///var/folders/sk/snm6bq6s697dwtlp3wsg0_ww0000gn/T/.org.chromium.Chromium.5gMscg/public/js/vendor/toastr.js.map Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///var/folders/sk/snm6bq6s697dwtlp3wsg0_ww0000gn/T/.org.chromium.Chromium.5gMscg/public/js/vendor/angular.min.js.map Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///var/folders/sk/snm6bq6s697dwtlp3wsg0_ww0000gn/T/.org.chromium.Chromium.5gMscg/public/js/vendor/angular-sanitize.min.js.map Failed to load resource: net::ERR_FILE_NOT_FOUND
https://api.soundcloud.com/tracks/279863797/stream?client_id=342b8a7af638944906dcdb46f9d56d98 Failed to load resource: the server responded with a status of 429 (Too Many Requests)`

**Comment by Keepco** [comment]
Same error. AFAIK this is caused because Soundcloud doesn't allow unlimited playback for clients other than their own. When I visit one of the links it says:
{"errors":[{"meta":{"rate_limit":{"bucket":"by-client","max_nr_of_requests":65000,"time_window":"PT24H","name":"plays"},"remaining_requests":0,"reset_time":"2016/08/30 05:08:57 +0000"}}]}
So I guess that playback should work once the counter is reset

**Comment by wb9688** [comment]
This is the second time we hit the rate limit. We should really implement
caching. We should also make it possible to use you own API key…

**Comment by bryguy** [comment]
An enterprising user could always [register](http://soundcloud.com/you/apps) their "own" soundcloud app, then fire up developer tools, head to the console tab, and set `window.scClientId` to the "Client ID" for that new app. Obviously this is a short term solution as it won't persist when opening/closing the SoundNode. But hey, it got the tunes streaming again for me right now. :)

Longer term, you could add a field in settings where users can enter this value so that it _would_ be persistent. Just use that value if it exists instead of the value returned from 'http://sc-redirect.herokuapp.com/'. (Although maybe that brings up security concerns or is an api terms of use violation, I don't know.)

**Comment by Pitros** [comment]
@wb9688 using own API key is good idea, but if we just had serval API keys which would be randomly assigned on login, rate limits would not bother us for a long time. And that would just took few minutes to make (small change on sc-redirect.herokuapp.com)

**Comment by wb9688** [comment]
@bryguy I know, there's also a setting in window.localStorage if I remember
correctly…

---

@pjotr Yeah, but then we still have the same problem with the users from
before the change unless you're going to remove the current API key…

**Comment by bryguy** [comment]
@wb9688 Of course, I should have thought of that/looked a little closer. Silly me!

```
window.localStorage.scClientId = "YOUR_PERSONAL_SOUNDCLOUD_CLIENT_ID";
```

Now it persists across app launches. Thanks!
