### ISSUE TITLE
Can't get beyond the "Authenticating" window

### ISSUE THREAD

**Issue by ferassobh** [Soundnode/soundnode-app#895]
It seems that there are two windows back to back. One is black with the message "Authenticating your Soundcloud account" and another white one with no info at all. I have left it for hours but I still can't get a response.

**Comment by garfbargle** [comment]
Same issue.

**Comment by weblancaster** [comment]
@ferassobh what OS are you using? can you quit and restart the app please? (same for you @garfbargle )

**Comment by garfbargle** [comment]
@weblancaster Hey, I'm using mac os x sierra. I was having the same issue on both of my computers (both running macOS sierra) and it started the day that soundcloud was having the SSL certificates problem. I've since been able to get the app out of the weird state on my other computer by deleting the app and re downloading a new version. However I've not be able to have the same success on this computer. I also deleted ~/library/application_support/soundnode and still have the issue.

**Comment by garfbargle** [comment]
Note: The reason I was able to get out of the weird state on my other computer was because when I returned to my computer, the app was still open and although no data was loaded I could click the 'logout' button. Once I logged out and tried to login it failed and gave me the black/white screens. However, after deleting the app and redownloading it worked.

**Comment by weblancaster** [comment]
yeah that's odd.. I'm re-writing how the core of the app works so in the next couple of days I'm going to have migrated everything and hoping that will be much better.

**Comment by weblancaster** [comment]
closing this issue.. you can follow the migration here #894
