### ISSUE TITLE
[possible solution] Soundcloud API being used up

### ISSUE THREAD

**Issue by The-Unnamed-Engineer** [Soundnode/soundnode-app#916]
I really like using Soundnode but after about an hour of playing music it stops playing. I am not getting an error message yet my current suspect is the SoundCloud API being used up. My initial plan was to apply for an API key of my own to use but quickly realized this wasn't possible. I did however learn of a set of audio grabbing libraries with Soundcloud capability called [Youtube-dl](https://rg3.github.io/youtube-dl/). they might just be the solution to the API limit you are running into.

I am on the windows version of Soundnode.

**Comment by valevalorin** [comment]
I think having users apply for their own API key is a pretty good solution. It is possible to do, but could require some changes to redirect-sc.herokuapp.com. 

One way to do this would be that users are forced to host their own redirect/callback. This is technically possible now if your fork the app and change the authentication code to point to your service instead of the soundnode one, and could be a worthwhile solution for tech savvy users who don't want to deal with the API limit.

A way that's easier for general users would be to allow the user to set their API key and secret in the UI. Then it could pass those parameters to redirect-sc.herokuapp.com, the redirect reads them in and auths you for your own application, and gives that auth token back to Soundnode to use. This is a pretty good solution but security could be considered an issue since you have to pass your API key and secret every time you auth. But, if it's run over https it shouldn't be a big deal.

If the security for the previous solution is unexceptable, we could make users make a 'Soundnode' account. Then either via the website or the Soundnode app, you could have the users set their key and secret which gets stored server-side. Then when you auth to the redirect you send your Soundnode account information, which the redirect uses to look up your API key and secret, which it then uses to create a token for the user's application, which is then passed back to the Soundnode app for use.

I'd like to get the devs thoughts on this.

**Comment by The-Unnamed-Engineer** [comment]
I did apply for an API key. it took them 8 days to approve it. I think if they just set it up to rotate maybe 5 API keys we would be able to work with that...

**Comment by weblancaster** [comment]
Luck you @The-Unnamed-Engineer because they did not approve my new request.

**Comment by valevalorin** [comment]
Why were you applying for a new key?

**Comment by weblancaster** [comment]
@valevalorin so I can switch them when one hit the API limit.

**Comment by killianbrackey** [comment]
Is the source for the heroku app available anywhere for those that would want to self host or work on an implementation of one of these proposed solutions?  I would definitely be willing to put some time into that, if at the very least to have a longer playing time for myself, but definitely for the community as well.

**Comment by weblancaster** [comment]
@killianbrackey it's open now. https://github.com/Soundnode/sc-oauth

follow #802 to continue this conversation.
