### ISSUE TITLE
soundnode not working on Archlinux x64

### ISSUE THREAD

**Issue by TuXbOy06** [Soundnode/soundnode-app#983]
Hello,

After installing soundnode music search is not working...
We can search for a music but when clicking on the music to listen nothing happen...

Can you help please...

**Comment by RedHope** [comment]
#802 ?

**Comment by TuXbOy06** [comment]
Hello,

Nothing to do with this issue...

**Comment by pwittchen** [comment]
The same issue happens on Ubuntu 16.04 with Gnome. I cannot play any song.

**Comment by TuXbOy06** [comment]
Is this project still alive?

**Comment by weblancaster** [comment]
@TuXbOy06 Yes but not actively maintained anymore since Soundcloud hasn't removed the rate limit and users went down from 5k daily to 1k (or less some days).

I also need to try find space for this project but my other projects are more high priority at the moment so it's always in the bottom of the list.

My apologies. I will try finding time this week to do a new release because there is a lot of work done that hasn't been release yet.

Thanks.
